#!/bin/bash

echo "[info] Running vulcan for k8s installaion."
#KAIS_SAVEINSTALLATIONFILES=n
#KAIS_VERBOSELEVEL=5
#KAIS_NEWBIEMODE=n
echo ${KAIS_SAVEINSTALLATIONFILES}
echo ${KAIS_VERBOSELEVEL}
echo ${KAIS_NEWBIEMODE}
